#! /bin/bash

## generated by : /lustre/fs4/home/ulee/cactus-bin-v2.3.0/cactus_env/bin/cactus-prepare dros.txt --outDir steps-output --outSeqFile steps-output/dros.txt --outHal steps-output/dros.hal --jobStore jobstore
## date : 2022-12-14 10:50:06.950789
## cactus commit : e01b4451f637d7eced1038d161fee05d20ef3546


## Preprocessor
cactus-preprocess jobstore/0 dros.txt steps-output/dros.txt --inputNames ana mel yak --realTimeLogging --logInfo --retryCount 0
cactus-preprocess jobstore/1 dros.txt steps-output/dros.txt --inputNames ere sim sec --realTimeLogging --logInfo --retryCount 0

## Alignment

### Round 0
cactus-blast jobstore/2 steps-output/dros.txt steps-output/1.cigar --root 1
cactus-align jobstore/3 steps-output/dros.txt steps-output/1.cigar steps-output/1.hal --root 1  --maxCores 2
hal2fasta steps-output/1.hal 1 --hdf5InMemory > steps-output/1.fa

cactus-blast jobstore/4 steps-output/dros.txt steps-output/3.cigar --root 3
cactus-align jobstore/5 steps-output/dros.txt steps-output/3.cigar steps-output/3.hal --root 3  --maxCores 2
hal2fasta steps-output/3.hal 3 --hdf5InMemory > steps-output/3.fa

### Round 1
cactus-blast jobstore/6 steps-output/dros.txt steps-output/2.cigar --root 2
cactus-align jobstore/7 steps-output/dros.txt steps-output/2.cigar steps-output/2.hal --root 2  --maxCores 2
hal2fasta steps-output/2.hal 2 --hdf5InMemory > steps-output/2.fa

### Round 2
cactus-blast jobstore/8 steps-output/dros.txt steps-output/4.cigar --root 4
cactus-align jobstore/9 steps-output/dros.txt steps-output/4.cigar steps-output/4.hal --root 4  --maxCores 2
hal2fasta steps-output/4.hal 4 --hdf5InMemory > steps-output/4.fa

### Round 3
cactus-blast jobstore/10 steps-output/dros.txt steps-output/Anc0.cigar --root Anc0
cactus-align jobstore/11 steps-output/dros.txt steps-output/Anc0.cigar steps-output/dros.hal --root Anc0  --maxCores 2
hal2fasta steps-output/dros.hal Anc0 --hdf5InMemory > steps-output/Anc0.fa

## HAL merging
halAppendSubtree steps-output/dros.hal steps-output/4.hal 4 4 --merge --hdf5InMemory --hdf5InMemory
halAppendSubtree steps-output/dros.hal steps-output/2.hal 2 2 --merge --hdf5InMemory --hdf5InMemory
halAppendSubtree steps-output/dros.hal steps-output/1.hal 1 1 --merge --hdf5InMemory --hdf5InMemory
halAppendSubtree steps-output/dros.hal steps-output/3.hal 3 3 --merge --hdf5InMemory --hdf5InMemory